{"trial_id": "0001", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation", "default": "relu", "conditions": [], "values": ["relu", "tanh"], "ordered": false}}, {"class_name": "Int", "config": {"name": "first_units", "default": null, "conditions": [], "min_value": 1, "max_value": 120, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 5, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_0", "default": null, "conditions": [], "min_value": 1, "max_value": 120, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 1, "max_value": 120, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 1, "max_value": 120, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 1, "max_value": 120, "step": 5, "sampling": "linear"}}], "values": {"activation": "relu", "first_units": 91, "num_layers": 2, "units_0": 46, "units_1": 1, "units_2": 41, "units_3": 106, "tuner/epochs": 3, "tuner/initial_epoch": 0, "tuner/bracket": 2, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 173, in _try_build\n    size = maybe_compute_model_size(model)\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 463, in maybe_compute_model_size\n    params = [math.prod(p.shape) for p in model.trainable_weights]\n  File \"c:\\Users\\vaibh\\anaconda3\\envs\\myfirstpythonenv\\lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 463, in <listcomp>\n    params = [math.prod(p.shape) for p in model.trainable_weights]\nAttributeError: module 'math' has no attribute 'prod'\n"}